data2targets = list(
    "DC" = list("time", "time_last_token"),
    "NS" = list("time", "time_last_token"),
    "NS_MAZE" = list("time", "time_last_token"),
    "UCL" = list("ELAN","LAN","N400","EPNP","P600","PNP","RTfirstpass", "RTreread", "RTgopast", "self_paced_reading_time", "RTfirstpass_last_token", "RTreread_last_token", "RTgopast_last_token", "self_paced_reading_time_last_token", "N400_last_token", "P600_last_token", "EPNP_last_token", "PNP_last_token", "ELAN_last_token", "LAN_last_token"),
    "Fillers" = list("SPR_RT", "MAZE_RT", "FPRT", "SPR_RT_last_token", "MAZE_RT_last_token", "FPRT_last_token"),
    "S_N400" = list('Federmeier et al. (2007)', 'Hubbard et al. (2019)', 'Szewczyk & Federmeier (2022)', 'Szewczyk et al. (2022)', 'Wlotko & Federmeier (2012)'),
    "M_N400" = list('C3', 'C4', 'CP3', 'CP4', 'CPz', 'Cz', 'P3', 'P4', 'Pz', 'all'),
    "MECO\\/du" = list("time"),
    "MECO\\/ee" = list("time"),
    "MECO\\/en" = list("time"),
    "MECO\\/fi" = list("time"),
    "MECO\\/ge" = list("time"),
    "MECO\\/gr" = list("time"),
    "MECO\\/he" = list("time"),
    "MECO\\/it" = list("time"),
    "MECO\\/ko" = list("time"),
    "MECO\\/no" = list("time"),
    "MECO\\/ru" = list("time"),
    "MECO\\/sp" = list("time"),
    "MECO\\/tr" = list("time"),
    "ZuCO" = list("time", "N400", "time_last_token", "N400_last_token")
)

models <- c(
    "gpt2",
    "gpt2-medium",
    "gpt2-large",
    "gpt2-xl",
    "opt-125m",
    "opt-1.3b",
    "opt-2.7b",
    "opt-6.7b",
    "opt-13b",
    "opt-30b",
    "opt-66b",
    "pythia-14m",
    'pythia-31m',
    "pythia-70m-deduped",
    "pythia-160m-deduped",
    "pythia-410m-deduped",
    "pythia-1b-deduped",
    "pythia-1.4b-deduped",
    "pythia-2.8b-deduped",
    "pythia-6.9b-deduped",
    "pythia-12b-deduped"
)

multilingual_models <- c(
    "xglm-564M",
    "xglm-1.7B",
    "xglm-2.9B",
    "xglm-4.5B",
    "xglm-7.5B"
)

tuned_models <- c(
    "gpt2",
    "gpt2-large",
    "gpt2-xl",
    "opt-125m",
    "opt-1.3b",
    "opt-6.7b",
    "pythia-70m-deduped",
    "pythia-160m-deduped",
    "pythia-410m-deduped",
    "pythia-1b-deduped-v0",
    "pythia-1.4b-deduped",
    "pythia-2.8b-deduped",
    "pythia-6.9b-deduped",
    "pythia-12b-deduped"
)

models2params = c(
"gpt2" =  124000000,
"gpt2-medium" =  345000000,
"gpt2-large" =  774000000,
"gpt2-xl" =  1558000000,
"opt-125m" =  125000000,
"opt-1.3b" =  1300000000,
"opt-2.7b" =  2700000000,
"opt-6.7b" =  6700000000,
"opt-13b" =  13000000000,
"opt-30b" =  30000000000,
"opt-66b" =  66000000000,
"pythia-14m" =  14000000,
"pythia-31m" =  31000000,
"pythia-70m-deduped" =  70000000,
"pythia-160m-deduped" =  160000000,
"pythia-410m-deduped" =  410000000,
"pythia-1b-deduped" =  1000000000,
"pythia-1b-deduped-v0" =  1000000000,
"pythia-1.4b-deduped" =  1400000000,
"pythia-2.8b-deduped" =  2800000000,
"pythia-6.9b-deduped" =  6900000000,
"pythia-12b-deduped" =  12000000000,
"xglm-564M" =  564000000,
"xglm-1.7B" =  1700000000,
"xglm-2.9B" =  2900000000,
"xglm-4.5B" =  4500000000,
"xglm-7.5B" =  7500000000
)

models2family = c(
    "gpt2" =  "gpt2",
    "gpt2-medium" =  "gpt2",
    "gpt2-large" =  "gpt2",
    "gpt2-xl" =  "gpt2",
    "opt-125m" =  "opt",
    "opt-1.3b" =  "opt",
    "opt-2.7b" =  "opt",
    "opt-6.7b" =  "opt",
    "opt-13b" =  "opt",
    "opt-30b" =  "opt",
    "opt-66b" =  "opt",
    "pythia-14m" =  "pythia",
    "pythia-31m" =  "pythia",
    "pythia-70m-deduped" =  "pythia",
    "pythia-160m-deduped" =  "pythia",
    "pythia-410m-deduped" =  "pythia",
    "pythia-1b-deduped" =  "pythia",
    "pythia-1b-deduped-v0" =  "pythia",
    "pythia-1.4b-deduped" =  "pythia",
    "pythia-2.8b-deduped" =  "pythia",
    "pythia-6.9b-deduped" =  "pythia",
    "pythia-12b-deduped" =  "pythia",
    "xglm-564M" =  "xglm",
    "xglm-1.7B" =  "xglm",
    "xglm-2.9B" =  "xglm",
    "xglm-4.5B" =  "xglm",
    "xglm-7.5B" =  "xglm"
)
models2color = c(
    "gpt2" =  "darkblue",
    "gpt2-medium" =  "darkblue",
    "gpt2-large" =  "darkblue",
    "gpt2-xl" =  "darkblue",
    "opt-125m" =  "darkgreen",
    "opt-1.3b" =  "darkgreen",
    "opt-2.7b" =  "darkgreen",
    "opt-6.7b" =  "darkgreen",
    "opt-13b" =  "darkgreen",
    "opt-30b" =  "darkgreen",
    "opt-66b" =  "darkgreen",
    "pythia-14m" =  "darkorange",
    "pythia-31m" =  "darkorange",
    "pythia-70m-deduped" =  "darkorange",
    "pythia-160m-deduped" =  "darkorange",
    "pythia-410m-deduped" =  "darkorange",
    "pythia-1b-deduped" =  "darkorange",
    "pythia-1b-deduped-v0" =  "darkorange",
    "pythia-1.4b-deduped" =  "darkorange",
    "pythia-2.8b-deduped" =  "darkorange",
    "pythia-6.9b-deduped" =  "darkorange",
    "pythia-12b-deduped" =  "darkorange",
    "xglm-564M" =  "darkblue",
    "xglm-1.7B" =  "darkblue",
    "xglm-2.9B" =  "darkblue",
    "xglm-4.5B" =  "darkblue",
    "xglm-7.5B" =  "darkblue"
)

models2size = c(
    "gpt2" =  10,
    "gpt2-medium" =  20,
    "gpt2-large" =  30,
    "gpt2-xl" =  40,
    "opt-125m" =  10,
    "opt-1.3b" =  40,
    "opt-2.7b" =  50,
    "opt-6.7b" =  60,
    "opt-13b" =  70,
    "opt-30b" =  80,
    "opt-66b" =  90,
    "pythia-14m" =  8,
    "pythia-31m" =  12,
    "pythia-70m-deduped" =  15,
    "pythia-160m-deduped" =  20,
    "pythia-410m-deduped" =  30,
    "pythia-1b-deduped" =  40,
    "pythia-1b-deduped-v0" =  40,
    "pythia-1.4b-deduped" =  40,
    "pythia-2.8b-deduped" =  50,
    "pythia-6.9b-deduped" =  60,
    "pythia-12b-deduped" =  70,
    "xglm-564M" =  20,
    "xglm-1.7B" =  30,
    "xglm-2.9B" =  40,
    "xglm-4.5B" =  50,
    "xglm-7.5B" =  60
)

model2marker= c(
    "gpt2" =  "o",
    "gpt2-medium" =  "o",
    "gpt2-large" =  "o",
    "gpt2-xl" =  "o",
    "opt-125m" =  "s",
    "opt-1.3b" =  "s",
    "opt-2.7b" =  "s",
    "opt-6.7b" =  "s",
    "opt-13b" =  "s",
    "opt-30b" =  "s",
    "opt-66b" =  "s",
    "pythia-14m" =  "D",
    "pythia-31m" =  "D",
    "pythia-70m-deduped" =  "D",
    "pythia-160m-deduped" =  "D",
    "pythia-410m-deduped" =  "D",
    "pythia-1b-deduped" =  "D",
    "pythia-1b-deduped-v0" =  "D",
    "pythia-1.4b-deduped" =  "D",
    "pythia-2.8b-deduped" =  "D",
    "pythia-6.9b-deduped" =  "D",
    "pythia-12b-deduped" =  "D",
    "xglm-564M" =  "s",
    "xglm-1.7B" =  "s",
    "xglm-2.9B" =  "s",
    "xglm-4.5B" =  "s",
    "xglm-7.5B" =  "s"
)

all_datasets <- c(
 'NS_time',
 'NS_time_last_token',
 'NS_MAZE_time',
 'NS_MAZE_time_last_token',
 'DC_time',
 'DC_time_last_token',
 'Fillers_SPR_RT',
 'Fillers_SPR_RT_last_token',
 'Fillers_FPRT',
 'Fillers_FPRT_last_token',
 'Fillers_MAZE_RT',
 'Fillers_MAZE_RT_last_token',
 'M_N400_all',
 'M_N400_C3',
 'M_N400_C4',
 'M_N400_CP3',
 'M_N400_CP4',
 'M_N400_CPz',
 'M_N400_Cz',
 'M_N400_P3',
 'M_N400_P4',
 'M_N400_Pz',
 'S_N400_Federmeier_et_al._(2007)',
 'S_N400_Hubbard_et_al._(2019)',
 'S_N400_Szewczyk_&_Federmeier_(2022)',
 'S_N400_Szewczyk_et_al._(2022)',
 'S_N400_Wlotko_&_Federmeier_(2012)',
 'UCL_ELAN',
 'UCL_ELAN_last_token',
 'UCL_EPNP',
 'UCL_EPNP_last_token',
'UCL_LAN',
'UCL_LAN_last_token',
'UCL_N400',
'UCL_N400_last_token',
'UCL_P600',
'UCL_P600_last_token',
'UCL_PNP',
'UCL_PNP_last_token',
'UCL_RTfirstpass',
'UCL_RTreread',
'UCL_RTgopast',
'UCL_self_paced_reading_time',
'UCL_RTfirstpass_last_token',
'UCL_RTreread_last_token',
'UCL_RTgopast_last_token',
'UCL_self_paced_reading_time_last_token',
'ZuCO_time',
'ZuCO_N400'
)

data2method = c(
    'NS_time' =  'SPR',
    'NS_time_last_token' =  'SPR',
    'NS_MAZE_time' =  'MAZE',
    'NS_MAZE_time_last_token' =  'MAZE',
    'DC_time' =  'FPGD',
    'DC_time_last_token' =  'FPGD',
    'Fillers_SPR_RT' =  'SPR',
    'Fillers_FPRT' =  'FPGD',
    'Fillers_MAZE_RT' =  'MAZE',
    'Fillers_SPR_RT_last_token' =  'SPR',
    'Fillers_FPRT_last_token' =  'FPGD',
    'Fillers_RRT_last_token' =  'SPGD',
    'Fillers_MAZE_RT_last_token' =  'MAZE',
    'M_N400_C3' =  'N400',
    'M_N400_C4' =  'N400',
    'M_N400_CP3' =  'N400',
    'M_N400_CP4' =  'N400',
    'M_N400_CPz' =  'N400',
    'M_N400_Cz' =  'N400',
    'M_N400_P3' =  'N400',
    'M_N400_P4' =  'N400',
    'M_N400_Pz' =  'N400',
    'M_N400_all' =  'N400',
    'S_N400_Federmeier_et_al._(2007)' =  'N400',
    'S_N400_Hubbard_et_al._(2019)' =  'N400',
    'S_N400_Szewczyk_&_Federmeier_(2022)' =  'N400',
    'S_N400_Szewczyk_et_al._(2022)' =  'N400',
    'S_N400_Wlotko_&_Federmeier_(2012)' =  'N400',
    'UCL_ELAN' =  'ELAN',
    'UCL_ELAN_last_token' =  'ELAN',
    'UCL_EPNP' =  'EPNP',
    'UCL_EPNP_last_token' =  'EPNP',
    'UCL_LAN' =  'LAN',
    'UCL_LAN_last_token' =  'LAN',
    'UCL_N400' =  'N400',
    'UCL_N400_last_token' =  'N400',
    'UCL_P600' =  'P600',
    'UCL_P600_last_token' =  'P600',
    'UCL_PNP' =  'PNP',
    'UCL_PNP_last_token' =  'PNP',
    'UCL_RTfirstpass' =  'FPGD',
    'UCL_RTreread' =  'SPGD',
    'UCL_RTgopast' =  'GP',
    'UCL_self_paced_reading_time' =  'SPR',
    'UCL_RTfirstpass_last_token' =  'FPGD',
    'UCL_RTreread_last_token' =  'SPGD',
    'UCL_RTgopast_last_token' =  'GP',
    'UCL_self_paced_reading_time_last_token' =  'SPR',
    "du_time" =  "Du",
    "ee_time" =  "Ee",
    "en_time" =  "En",
    "fi_time" =  "Fi",
    "ge_time" =  "Ge",
    "gr_time" =  "Gr",
    "he_time" =  "He",
    "it_time" =  "It",
    "ko_time" =  "Ko",
    "no_time" =  "No",
    "ru_time" =  "Ru",
    "sp_time" =  "Sp",
    "tr_time" =  "Tr",
    "ZuCO_time" =  "FPGD",
    "ZuCO_N400" =  "N400"
)

data2cite = c(
    'NS_time' =  '~\\cite{Futrell2021-wr}',
    'NS_time_last_token' =  '~\\cite{Futrell2021-wr}',
    'NS_MAZE_time' =  '~\\cite{Boyce2023AmazeON}',
    'NS_MAZE_time_last_token' =  '~\\cite{Boyce2023AmazeON}',
    'DC_time' =  '~\\cite{kennedy2003dundee}',
    'DC_time_last_token' =  '~\\cite{kennedy2003dundee}',
    'Fillers_SPR_RT' =  '~\\cite{Vasishth2010-ji}',
    'Fillers_FPRT' =  '~\\cite{Vasishth2010-ji}',
    'Fillers_MAZE_RT' =  '~\\cite{Hahn2022-ib}',
    'Fillers_SPR_RT_last_token' =  '~\\cite{Vasishth2010-ji}',
    'Fillers_FPRT_last_token' =  '~\\cite{Vasishth2010-ji}',
    'Fillers_MAZE_RT_last_token' =  '~\\cite{Hahn2022-ib}',
    'M_N400_C3' =  '~\\cite{michaelov2023strong}',
    'M_N400_C4' =  '~\\cite{michaelov2023strong}',
    'M_N400_CP3' =  '~\\cite{michaelov2023strong}',
    'M_N400_CP4' =  '~\\cite{michaelov2023strong}',
    'M_N400_CPz' =  '~\\cite{michaelov2023strong}',
    'M_N400_Cz' =  '~\\cite{michaelov2023strong}',
    'M_N400_P3' =  '~\\cite{michaelov2023strong}',
    'M_N400_P4' =  '~\\cite{michaelov2023strong}',
    'M_N400_Pz' =  '~\\cite{michaelov2023strong}',
    'M_N400_all' =  '~\\cite{michaelov2023strong}',
    'S_N400_Federmeier_et_al._(2007)' =  '~\\cite{Federmeier2007-qg}',
    'S_N400_Hubbard_et_al._(2019)' =  '~\\cite{Hubbard2019-vz}',
    'S_N400_Szewczyk_&_Federmeier_(2022)' =  '~\\cite{Szewczyk2022-ds}',
    'S_N400_Szewczyk_et_al._(2022)' =  '~\\cite{Szewczyk2022-cd}',
    'S_N400_Wlotko_&_Federmeier_(2012)' =  '~\\cite{Wlotko2012-eh}',
    'UCL_ELAN' =  '~\\cite{FRANK20151}',
    'UCL_ELAN_last_token' =  '~\\cite{FRANK20151}',
    'UCL_EPNP' =  '~\\cite{FRANK20151}',
    'UCL_EPNP_last_token' =  '~\\cite{FRANK20151}',
    'UCL_LAN' =  '~\\cite{FRANK20151}',
    'UCL_LAN_last_token' =  '~\\cite{FRANK20151}',
    'UCL_N400' =  '~\\cite{FRANK20151}',
    'UCL_N400_last_token' =  '~\\cite{FRANK20151}',
    'UCL_P600' =  '~\\cite{FRANK20151}',
    'UCL_P600_last_token' =  '~\\cite{FRANK20151}',
    'UCL_PNP' =  '~\\cite{FRANK20151}',
    'UCL_PNP_last_token' =  '~\\cite{FRANK20151}',
    'UCL_RTfirstpass' =  '~\\cite{frank2013reading}',
    'UCL_RTreread' =  '~\\cite{frank2013reading}',
    'UCL_RTgopast' =  '~\\cite{frank2013reading}',
    'UCL_self_paced_reading_time' =  '~\\cite{frank2013reading}',
    'UCL_RTfirstpass_last_token' =  '~\\cite{frank2013reading}',
    'UCL_RTreread_last_token' =  '~\\cite{frank2013reading}',
    'UCL_RTgopast_last_token' =  '~\\cite{frank2013reading}',
    'UCL_self_paced_reading_time_last_token' =  '~\\cite{frank2013reading}',
    "du_time" =  "~\\cite{siegelman2022expanding}",
    "ee_time" =  "~\\cite{siegelman2022expanding}",
    "en_time" =  "~\\cite{siegelman2022expanding}",
    "fi_time" =  "~\\cite{siegelman2022expanding}",
    "ge_time" =  "~\\cite{siegelman2022expanding}",
    "gr_time" =  "~\\cite{siegelman2022expanding}",
    "he_time" =  "~\\cite{siegelman2022expanding}",
    "it_time" =  "~\\cite{siegelman2022expanding}",
    "ko_time" =  "~\\cite{siegelman2022expanding}",
    "no_time" =  "~\\cite{siegelman2022expanding}",
    "ru_time" =  "~\\cite{siegelman2022expanding}",
    "sp_time" =  "~\\cite{siegelman2022expanding}",
    "tr_time" =  "~\\cite{siegelman2022expanding}",
    "ZuCO_time" =  "~\\cite{Hollenstein2018-rm}",
    "ZuCO_N400" =  "~\\cite{Hollenstein2018-rm}"
)

data2stimuli = c(
    'NS_time' =  'NS',
    'NS_time_last_token' =  'NS',
    'NS_MAZE_time' =  'NS',
    'NS_MAZE_time_last_token' =  'NS',
    'DC_time' =  'DC',
    'DC_time_last_token' =  'DC',
    'Fillers_SPR_RT' =  'Fillers',
    'Fillers_FPRT' =  'Fillers',
    'Fillers_MAZE_RT' =  'Fillers',
    'Fillers_SPR_RT_last_token' =  'Fillers',
    'Fillers_FPRT_last_token' =  'Fillers',
    'Fillers_MAZE_RT_last_token' =  'Fillers',
    'M_N400_C3' =  'Michaelov+,\n2024',
    'M_N400_C4' =  'Michaelov+,\n2024',
    'M_N400_CP3' =  'Michaelov+,\n2024',
    'M_N400_CP4' =  'Michaelov+,\n2024',
    'M_N400_CPz' =  'Michaelov+,\n2024',
    'M_N400_Cz' =  'Michaelov+,\n2024',
    'M_N400_P3' =  'Michaelov+,\n2024',
    'M_N400_P4' =  'Michaelov+,\n2024',
    'M_N400_Pz' =  'Michaelov+,\n2024',
    'M_N400_all' =  'Michaelov+,\n2024',
    'S_N400_Federmeier_et_al._(2007)' =  'Federmeier+,\n2007',
    'S_N400_Hubbard_et_al._(2019)' =  'Hubbard+,\n2019',
    'S_N400_Szewczyk_&_Federmeier_(2022)' =  'S&F,2022',
    'S_N400_Szewczyk_et_al._(2022)' =  'Szewczyk+,\n2022',
    'S_N400_Wlotko_&_Federmeier_(2012)' =  'W&F,2012',
    'UCL_ELAN' =  'UCL',
    'UCL_ELAN_last_token' =  'UCL',
    'UCL_EPNP' =  'UCL',
    'UCL_EPNP_last_token' =  'UCL',
    'UCL_LAN' =  'UCL',
    'UCL_LAN_last_token' =  'UCL',
    'UCL_N400' =  'UCL',
    'UCL_N400_last_token' =  'UCL',
    'UCL_P600' =  'UCL',
    'UCL_P600_last_token' =  'UCL',
    'UCL_PNP' =  'UCL',
    'UCL_PNP_last_token' =  'UCL',
    'UCL_RTfirstpass' =  'UCL',
    'UCL_RTreread' =  'UCL',
    'UCL_RTgopast' =  'UCL',
    'UCL_self_paced_reading_time' =  'UCL',
    'UCL_RTfirstpass_last_token' =  'UCL',
    'UCL_RTreread_last_token' =  'UCL',
    'UCL_RTgopast_last_token' =  'UCL',
    'UCL_self_paced_reading_time_last_token' =  'UCL',
    "du_time" =  "MECO",
    "ee_time" =  "MECO",
    "en_time" =  "MECO",
    "fi_time" =  "MECO",
    "ge_time" =  "MECO",
    "gr_time" =  "MECO",
    "he_time" =  "MECO",
    "it_time" =  "MECO",
    "ko_time" =  "MECO",
    "no_time" =  "MECO",
    "ru_time" =  "MECO",
    "sp_time" =  "MECO",
    "tr_time" =  "MECO",
    "ZuCO_time" =  "ZuCO",
    "ZuCO_N400" =  "ZuCO"
)